plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lighty.sargospoofer'
    compileSdk 34

    defaultConfig {
        applicationId "com.lighty.sargospoofer"
        minSdk 27
        targetSdk 34
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17 -fno-rtti -fno-exceptions"
            }
        }
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1+"
        }
    }
}

// 替换 app/build.gradle 底部的 Zip 任务
tasks.register('zipMagiskModule', Zip) {
    dependsOn 'assembleRelease'
    destinationDirectory = layout.buildDirectory.dir("outputs/module")
    archiveFileName = "Zygisk-Sargo-Spoofer-Release.zip"

    // 1. 放入模块基础文件
    from("$rootDir/module") {
        include "module.prop", "customize.sh"
    }

    // 2. 放入编译好的 .so 文件
    from(layout.buildDirectory.dir("intermediates/stripped_native_libs/release/out/lib")) {
        include "**/*.so"
        eachFile { FileCopyDetails fcp ->
            // fcp.file.parentFile.name 会精准抓取当前的架构名（如 arm64-v8a）
            def abi = fcp.file.parentFile.name
            // 重新定义它在 Zip 里的绝对路径，直接放进 zygisk 目录并改名
            fcp.path = "zygisk/${abi}.so"
        }
        includeEmptyDirs = false
    }
}

tasks.whenTaskAdded { task ->
    if (task.name == 'assembleRelease') {
        task.finalizedBy 'zipMagiskModule'
    }
}