plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lighty.sargospoofer'
    compileSdk 34

    defaultConfig {
        applicationId "com.lighty.sargospoofer"
        minSdk 27
        targetSdk 34
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17 -fno-rtti -fno-exceptions"
            }
        }
        ndk {
            // Pixel 10 这种纯 64 位设备，只保留这一个就够了
            abiFilters 'arm64-v8a'
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1+"
        }
    }
}

tasks.register('zipMagiskModule', Zip) {
    dependsOn 'assembleRelease'
    destinationDirectory = layout.buildDirectory.dir("outputs/module")
    archiveFileName = "Zygisk-Sargo-Spoofer-Release.zip"

    // 1. 放入模块基础文件
    from("$rootDir/module") {
        include "module.prop", "customize.sh"
    }

    // 2. 放入 C++ 编译的 .so，并展平路径
    from(layout.buildDirectory.dir("intermediates/stripped_native_libs/release/out/lib")) {
        include "**/*.so"
        eachFile { FileCopyDetails fcp ->
            def abi = fcp.file.parentFile.name
            fcp.path = "zygisk/${abi}.so"
        }
        includeEmptyDirs = false
    }

    // 3. 把 Java 编译出来的 classes.dex 抽出来，塞进安装包
    from(zipTree(layout.buildDirectory.file("outputs/apk/release/app-release-unsigned.apk"))) {
        include "classes.dex"
    }
}

tasks.whenTaskAdded { task ->
    if (task.name == 'assembleRelease') {
        task.finalizedBy 'zipMagiskModule'
    }
}